---
- name: Show version
  hosts: all
  gather_facts: no
  
  tasks:
    - name: Show version
      ios_command:
        commands: show version
      register: result
    - true: msg="can up ver"
      when: "not ('Version 12.4' in result.stdout[0])"
