---
- name: Show version
  hosts: all
  gather_facts: no
  
  tasks:
    - name: run show version and check to see if output contains IOS
      ios_command:
        commands: show version
      register: output
    - name: debug filter
      debug:
        msg: "{{ output |parse_genie(command='show version', os='Cisco') }}"
