---
- name: Show version
  hosts: all
  gather_facts: no
  
  tasks:
    - name: run show version and check to see if output contains IOS
      ios_command:
        commands: show version
      register: result
      when: " ('Version {{12.4(24)T}}' in result.stdout)"
