---
- name: Show version
  hosts: all
  tasks:
    - name: run show version and check to see if output contains IOS
      ios_command:
        commands: show version
        wait_for: result[0] contains IOS
    - debug: var=result[0].stdout_lines
