---
- name: Show version
  hosts: all
  gather_facts: no
  
  tasks:
    - name: run show version and check to see if output contains IOS
      ios_command:
        commands: show version
      register: result
    - debug: var=result.stdout_lines
      when: " ('Version {{version}}' in result.stdout)"
